create table IF NOT EXISTS users (
  name varchar(100) primary key,
  email varchar(100) not null,
  grade int default 0 not null,
  lastname varchar(200) default null,
  attr_1 varchar(20) default null,
  attr_2 varchar(20) default null,
  attr_3 varchar(20) default null,
  attr_4 varchar(20) default null,
  attr_5 varchar(20) default null,
  attr_6 varchar(20) default null,
  attr_7 varchar(20) default null,
  attr_8 varchar(20) default null,
  attr_9 varchar(20) default null,
  attr_11 varchar(20) default null,
  attr_12 varchar(20) default null,
  attr_13 varchar(20) default null,
  attr_14 varchar(20) default null,
  attr_15 varchar(20) default null,
  attr_16 varchar(20) default null,
  attr_17 varchar(20) default null,
  attr_18 varchar(20) default null,
  attr_19 varchar(20) default null,
  attr_20 varchar(20) default null,
  attr_21 varchar(20) default null,
  attr_22 varchar(20) default null,
  attr_23 varchar(20) default null,
  attr_24 varchar(20) default null,
  attr_25 varchar(20) default null,
  attr_26 varchar(20) default null,
  attr_27 varchar(20) default null,
  attr_28 varchar(20) default null,
  attr_29 varchar(20) default null,
  attr_30 varchar(20) default null,
  attr_31 varchar(20) default null,
  attr_32 varchar(20) default null,
  attr_33 varchar(20) default null,
  attr_34 varchar(20) default null,
  attr_35 varchar(20) default null,
  attr_36 varchar(20) default null,
  attr_37 varchar(20) default null,
  attr_38 varchar(20) default null,
  attr_39 varchar(20) default null,
  attr_40 varchar(20) default null,
  attr_41 varchar(20) default null,
  attr_42 varchar(20) default null,
  attr_43 varchar(20) default null,
  attr_44 varchar(20) default null,
  attr_45 varchar(20) default null,
  attr_46 varchar(20) default null,
  attr_47 varchar(20) default null,
  attr_48 varchar(20) default null,
  attr_49 varchar(20) default null,
  attr_50 varchar(20) default null,
  attr_51 varchar(20) default null,
  attr_52 varchar(20) default null,
  attr_53 varchar(20) default null,
  attr_54 varchar(20) default null,
  attr_55 varchar(20) default null,
  attr_56 varchar(20) default null,
  attr_57 varchar(20) default null,
  attr_58 varchar(20) default null,
  attr_59 varchar(20) default null
);

--insert into users values('demo', 'demo@mail.com', 1);
--insert into users values('admin', 'admin@mail.com', 2);
